---
# - name: DEBUG
#   debug:
#     msg: "{{ item }}"
#   loop: "{{ users_in_groups }}"

- name: USER | Create user
  ansible.builtin.user:
    append: "{{ item.append | default('False') }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    comment: "{{ item.state | default('\"Created by Ansible at ' + now(utc=false,fmt='%d.%m.%Y %H-%M-%S') + '\"') }}"
    password: "!"
    update_password: "always"
    password_lock: true
    shell: "{{ item.shell | default(omit) }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups | default(omit) }}"
    create_home: true
    system: "{{ item.system | default(false)}}"
    force: true
    remove: "{{ item.remove | default(true) }}"
  loop: "{{ users_in_groups }}"

- name: "USER | Add SSH keys"
  ansible.posix.authorized_key:
    comment: "Ansible managed {{ item.name }}@{{ item.group }}"
    exclusive: true
    key: "{{ item.ssh_keys | join('\n') }}"
    follow: false
    user: "{{ item.name }}"
    manage_dir: true
    key_options: "{{ item.ssh_key_options | default(omit) }}"
    state: present
  loop: "{{ users_in_groups }}"
  when:
    - ( item.state | default('present') ) != 'absent'
    - ( item.system | default(false) ) != true